### ISSUE TITLE
V3版本vpc不完整

### ISSUE THREAD

**Issue by anyharding** [TencentCloud/tencentcloud-sdk-python#1]
缺少
DescribeVpcEx
https://cloud.tencent.com/document/api/215/1372

DescribeSubnetEx
https://cloud.tencent.com/document/api/215/1371

**Comment by zqfan** [comment]
新版本和旧版本并非是一一对应的，DescribeVpcEx是没有版本管理的旧版迫不得已搞出来的，建议现在使用2017-03-12版本的 DescribeVpcs https://cloud.tencent.com/document/api/215/15778 和 DescribeSubnets https://cloud.tencent.com/document/api/215/15784
