### ISSUE TITLE
params 是个列表对象

### ISSUE THREAD

**Issue by wang765256860** [TencentCloud/tencentcloud-sdk-python#104]
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/c2dd67f1eefd6097f2d1e7964b2d8ace58eb5645/tencentcloud/monitor/v20180724/models.py#L847

![image](https://user-images.githubusercontent.com/16058207/120608289-9b49d880-c483-11eb-94f6-56ad2a270c6f.png)

**Comment by zqfan** [comment]
params都应该是字典类型，这种情况应该是业务后端返回的类型和接口定义不一致导致的，可以到控制台工单系统给云监控产品反馈，要求他们纠正后端返回，保持和文档中一致
