### ISSUE TITLE
OCR的示例是 ImageURL, 可否提供ImageBase64的做法?

### ISSUE THREAD

**Issue by viponedream** [TencentCloud/tencentcloud-sdk-python#109]
req = models.GeneralFastOCRRequest()
    req.ImageUrl = "https://mc.qcloudimg.com/static/img/6d4f1676deba26377d4303a462ca5074/image.png"
    resp = client.GeneralFastOCR(req)
    print(resp.to_json_string())

有时需要本地文件.而不是远程的url, 谢谢。

**Comment by zqfan** [comment]
重复问题
