### ISSUE TITLE
使用环境变量的方式添加代理报错

### ISSUE THREAD

**Issue by wqh17101** [TencentCloud/tencentcloud-sdk-python#117]
![image](https://user-images.githubusercontent.com/26429138/139787251-a424c2d3-b1c3-4f6b-a93e-d8dfe0d59536.png)

tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:ClientNetworkError message:[WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。 requestId:None

[TencentCloudSDKException] code:ClientNetworkError message:[WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。 requestId:None

**Comment by zqfan** [comment]
按道理不会报权限错，sdk是个客户端。
还是说你是在搭一个服务端？如果是这样的 话，你可能得用管理员权限运行

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/139806023-221dab40-262a-4710-9764-1974e46adee6.png)
我用管理员似乎也不行。
另外这个407是啥意思

**Comment by zqfan** [comment]
407是代理需要指定账号密码，例如http://username:password@hostname:port

**Comment by wqh17101** [comment]
可是这是一个脚本里的呀，如果需要账号密码应该每条都报这个错才对呀

**Comment by wqh17101** [comment]
soga，找到问题了，不是你们的问题，407是代理地址写错了，WinError 10013是我这边自己的网关做了上传图片限制，被拦截了
