### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by zqfan** [TencentCloud/tencentcloud-sdk-python#13]
TencentCloudSDKException] code:ClientNetworkError message:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) requestId:None

这个问题该怎么解决？使用的是python3

CentOS Linux release 7.0.1406 (Core)
环境就是tencentcloud-sdk-python 3.0.17 ,  Python 3.5.2
/etc/ssl/certs/ca-certificates.crt
这个文件没有
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by zqfan** [comment]
user reported a mac instance, curl & python requests work well.

**Comment by freidenker** [comment]
> user reported a mac case, curl & python requests work well.
> 
> [TencentCloudSDKException] code:ClientNetworkError message:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) requestId:None
> 
> mac os high sierra 10.13.5
> python 3.6.5
> openssl 1.0.21

same issue with you.

**Comment by lovebaicai** [comment]
You have to do this：
```
/Applications/Python\ 3.6/Install\ Certificates.command
```
link: [https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c](url)

**Comment by zqfan** [comment]
@lovebaicai Thanks for sharing this important information, Mac users will be glad to know it.

**Comment by thetachan** [comment]
better solution:
# 解决腾讯自签名证书问题 message:[SSL: CERTIFICATE_VERIFY_FAILED]
import ssl
ssl._create_default_https_context=ssl._create_unverified_context

**Comment by zqfan** [comment]
> better solution:
> 
> # 解决腾讯自签名证书问题 message:[SSL: CERTIFICATE_VERIFY_FAILED]
> import ssl ssl._create_default_https_context=ssl._create_unverified_context

这是不安全的。
我们最近刚发布一个版本，使用certifi管理证书文件。这个问题已经可以解决了。
