### ISSUE TITLE
[疑问]关于获取预留的环境变量

### ISSUE THREAD

**Issue by lfywork** [TencentCloud/tencentcloud-sdk-python#131]
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/dd84344868d1276d618904dd1d088de93bed708e/examples/common_client/describe_instances.py#L26

这一行获取到的是None
使用os.environ.get("TENCENTCLOUD_SECRETID")能够获取到一个临时的值

**Comment by zqfan** [comment]
环境变量是需要自己去设置的，否则不可能有值，你这个环境是在哪儿呢？

**Comment by zqfan** [comment]
长时间没有信息提供，先关闭，有更新可以重开
