### ISSUE TITLE
python的示例代码，居然配的是c++的文档。

### ISSUE THREAD

**Issue by whm2300** [TencentCloud/tencentcloud-sdk-python#132]
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/546a113b374e61ba41ba50dc0b70ad5795ddf2e2/tencentcloud/cls/v20201016/cls_client.py#L2012

**Comment by zqfan** [comment]
官网上的api文档就是这么写的哈，如果api文档接口描述没有照顾到各个语言，就会是这个样子里。具体可以看看python sdk example目录下的cls示例，那个是针对cls的python示例
