### ISSUE TITLE
cvm 何时能支持按实例名模糊搜索？

### ISSUE THREAD

**Issue by NowAnti** [TencentCloud/tencentcloud-sdk-python#145]
我的实例命名格式为：appid-userid-idx，每次想按 appid-userid 搜索所有机器都不行，能否尽快支持模糊搜索？
PS：本来打算改成不加 idx 这样可以精确搜索到，但是批量创建时实例名又必定会自动加上索引，无语😓

**Comment by zqfan** [comment]
SDK只是对接口的封装，决定不了接口的功能。还请到腾讯云官网控制台工单系统，向云服务器cvm提工单咨询是否能支持哈。
