### ISSUE TITLE
Read time out

### ISSUE THREAD

**Issue by rmpku** [TencentCloud/tencentcloud-sdk-python#150]
[TencentCloudSDKException] code:ClientNetworkError message:HTTPSConnectionPool(host='fmu.tencentcloudapi.com', port=443)

When using the API to call the image filter, this error will occur (a single call will not report an error, only when it is called continuously). According to experience, it can still be used normally a few months ago. Has Tencent recently restricted the number of accesses to the API?

**Comment by zqfan** [comment]
It seems a network issue, usually it will recover automatically after some minutes. If it continue for a long time, run `ping fmu.tencentcloudapi.com` command to check the network quality, or you can report a ticket in TencentCloud Management Console to get some help.
