### ISSUE TITLE
requests>=2.27.0,<=2.28.0一定要这个吗？

### ISSUE THREAD

**Issue by chenjianjian** [TencentCloud/tencentcloud-sdk-python#155]
requests>=2.27.0,<=2.28.0一定要这个版本吗？2.23.0版本支持吗？为什么会限制那么死

**Comment by HS-Gray** [comment]
感谢反馈，当时我们sdk在开发的时候使用的requests库是27版本的，所以版本号就限制在27以上了，后续我们回对低版本的requests库做测试，如果通过了会降低版本

**Comment by daidi** [comment]
还有高版本也会有报错，/usr/local/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!

tencentcloud-sdk-python 3.0.920 requires requests<=2.28.0,>=2.27.0, but you have requests 2.31.0 which is incompatible.

**Comment by LKI** [comment]
现在 requests 到了 `2.31.0` 了，建议兼容一下高版本
