### ISSUE TITLE
是否有提供 DNSPOD 的自定義線路相關接口?

### ISSUE THREAD

**Issue by ken1882** [TencentCloud/tencentcloud-sdk-python#170]
如題，
我有找到 https://docs.dnspod.cn/api/custom-line-list/ 和嘗試呼叫 `DescribeCustomLineList`，但回傳
```
>>> client.call_json('DescribeCustomLineList')
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:InvalidAction message:The request action="DescribeCustomLineList" is invalid or not found in service="dnspod" and version="2021-03-23".
```
以及 https://www.tencentcloud.com/zh/document/product/598/57108 中的 `DescribeDomainCustomLineList` 但回傳
```
>>> client.call_json('DescribeDomainCustomLineList', {'Domain': 'mydomain.com'})
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:InternalError message:内部服务错误，请稍后重试。
```
請問該如何正確調用相關 api 接口？謝謝。

**Comment by zqfan** [comment]
此SDK仅支持公开在https://cloud.tencent.com/document/api 且标记了api3.0字样的接口。

你提到的第一个接口是非api3.0的，甚至不在腾讯云官网，因此sdk接收到服务端报错，接口找不到

第二个接口应该是国际站对应的接口，此接口能被调用，但是dnspod后端可能出问题了，导致服务端报了内部错误，如果需要排查，请到控制台工单系统提单咨询。

建议使用API Explorer（https://console.cloud.tencent.com/api/explorer）的在线调用和SDK代码生成功能调试调用接口，能有助于快速掌握调用方式
