### ISSUE TITLE
py3: AttributeError: 'TypeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by zqfan** [TencentCloud/tencentcloud-sdk-python#20]
python: 3.5.2
sdk: 3.0.32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/cvm/v20170312/describe_instances.py", line 55, in <module>
    resp = client.DescribeInstances(req)
  File "/home/zqfan/codeoa/zhiqiangfan/tencentcloud-sdk-python/tencentcloud/cvm/v20170312/cvm_client.py", line 628, in DescribeInstances
    raise TencentCloudSDKException(e.message, e.message)
AttributeError: 'TypeError' object has no attribute 'message'

**Comment by zqfan** [comment]
no more report over 1 year, close it for now

**Comment by ragreenburg** [comment]
`  File "C:\Users\Hank\Documents\Random Python Scripts\selenium_web_scrape\web_scrape.py", line 130, in <module>
    print(e.message, e.args)
AttributeError: 'TypeError' object has no attribute 'message'`
I just got the same error for what it's worth.

**Comment by zqfan** [comment]
@ragreenburg you can just use `print(e)`
