### ISSUE TITLE
SDK是否支持CDN刷新、预热等接口

### ISSUE THREAD

**Issue by eaglesbest** [TencentCloud/tencentcloud-sdk-python#24]
现在最新release的版本v20180606是否支持CDN刷新、预热等接口？

**Comment by zqfan** [comment]
sdk和官网文档是对齐的，如果cdn在官网未放出相关接口的文档，则sdk中不会包含。
具体到你这个问题而言，cdn刷新，预热接口暂未放出，并不支持

**Comment by eaglesbest** [comment]
好的，谢谢！
