### ISSUE TITLE
Has 'MultiPullVodFile' interface been removed from SDK3.0?

### ISSUE THREAD

**Issue by VersionHX** [TencentCloud/tencentcloud-sdk-python#26]
According to the API Doc [https://cloud.tencent.com/document/api/266/7817](https://cloud.tencent.com/document/api/266/7817) , uploading file by url is provided with interface 'MultiPullVodFile'. However,  I can not find this interface at 'tencentcloud-sdk-python-3.0.54/tencentcloud/vod/v20180717/vod_client.py'. Has it been removed??

**Comment by zqfan** [comment]
SDK 3.0 only provides access to API 3.0, the document you mentioned is only available in API 2.0. If you need this functionality in API 3.0 as well, please log in Tencent Cloud Management Console and report it to VOD product, after it lands in API 3.0, SDK will automatically include it in next release.
