### ISSUE TITLE
python命名实体识别sdk访问可以给个样例吗

### ISSUE THREAD

**Issue by Roshanson** [TencentCloud/tencentcloud-sdk-python#28]
python命名实体识别sdk访问可以给个样例吗

**Comment by zqfan** [comment]
可以试试这个工具：https://console.cloud.tencent.com/api/explorer

**Comment by Roshanson** [comment]
命名实体识别好像还没有新版的sdk， 我用了网上博客找的旧版的sdk访问方式，不并发的速度有点慢啊。。还有 官网文档坑有点大啊，新旧版sdk  不同模块的鉴权方式，最好都给个样例（python java这些常用的） 及时更新
