### ISSUE TITLE
TKE 2017 API

### ISSUE THREAD

**Issue by mattchan-tencent** [TencentCloud/tencentcloud-sdk-python#29]
Is the Kubernetes 2017 API supported? It is documented but I don't see it in the code. Thanks!

https://cloud.tencent.com/document/api/457/9458

**Comment by zqfan** [comment]
You can access it via QcloudApi module or https://github.com/qcloudapi/qcloudapi-sdk-python , module name is ccs, but SDK source code implements API 2017 in a different way comparing to API 3.0, you need to know the API's parameters from document and call it in an universal way such as https://github.com/QcloudApi/qcloudapi-sdk-python#%E7%A4%BA%E4%BE%8B
