### ISSUE TITLE
镜像分享ModifyImageSharePermission接口参数

### ISSUE THREAD

**Issue by liyk1024** [TencentCloud/tencentcloud-sdk-python#30]
你好，麻烦问下，镜像分享ModifyImageSharePermission这个啥时能添加分享有效时间的参数？

**Comment by zqfan** [comment]
需要api先具备这个能力，sdk才能支持。请到控制台提工单给云服务器这个产品，向他们提出这个需求。

**Comment by liyk1024** [comment]
好的，了解，多谢




------------------ 原始邮件 ------------------
发件人: "ZhiQiang Fan"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 上午10:44
收件人: "TencentCloud/tencentcloud-sdk-python"<tencentcloud-sdk-python@noreply.github.com>; 
抄送: "liyk"<1195461076@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TencentCloud/tencentcloud-sdk-python] 镜像分享ModifyImageSharePermission接口参数 (#30)




需要api先具备这个能力，sdk才能支持。请到控制台提工单给云服务器这个产品，向他们提出这个需求。
