### ISSUE TITLE
[TencentCloudSDKException] code:ClientNetworkError

### ISSUE THREAD

**Issue by Wini1680** [TencentCloud/tencentcloud-sdk-python#31]
[TencentCloudSDKException] code:ClientNetworkError message:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847) requestId:None

Ubuntu 18.04
python3.6
秘钥用的是API秘钥管理的SecretId和SecretKey
然而出现这个错误是什么情况呢？

**Comment by zqfan** [comment]
你的python是自己编译的吗？请参考下网上对python编译时ssl模块需要注意的事项

**Comment by Wini1680** [comment]
@zqfan 您好，不是自己编译的，就是用的demo里的test_ocr_generalocr.py, 更正一下，现在用python2.7版本出现如下错误：
`----------------------SEND REQ----------------------
{
    "msg": "sdk http post err", 
    "ret": -1, 
    "httpcode": -1
}
----------------------API FAIL----------------------`

**Comment by Wini1680** [comment]
@zqfan 您好，不是自己编译的，就是用的demo里的test_ocr_generalocr.py, 更正一下，现在用python2.7版本出现如下错误：
----------------------SEND REQ----------------------
{
    "msg": "sdk http post err", 
    "ret": -1, 
    "httpcode": -1
}
----------------------API FAIL----------------------

**Comment by Wini1680** [comment]
1.把测试代码中的os.environ.get直接换成了SecretID和SecretKey
2.加了句ssl._create_default_https_context=ssl._create_unverified_context
