### ISSUE TITLE
如何配置proxy

### ISSUE THREAD

**Issue by IcyW** [TencentCloud/tencentcloud-sdk-python#33]
tencentcloud的接口是否提供proxies的配置，如：
```

import requests

proxies = {
  "http": "http://10.10.1.10:3128",
  "https": "http://10.10.1.10:1080",
}

requests.get("http://example.org", proxies=proxies)
```

**Comment by zqfan** [comment]
目前是读取的环境变量https_proxy： https://github.com/TencentCloud/tencentcloud-sdk-python#%E4%BB%A3%E7%90%86

**Comment by feixiaohuijava** [comment]
如果用pycharm在Windows开发，如果设置了环境变量，需要你重启Pycharm之后再去运行程序，不然你读不到刚刚设置的环境变量~（IDE坑了我一个晚上）

**Comment by lc4t** [comment]
代理有账号密码，看起来SDK中并不支持

**Comment by zqfan** [comment]
export https_proxy="http://用户名:密码@代理IP:代理端口"
如果用户名和密码，可能需要urlencode下

**Comment by Instantnoodles-madman** [comment]
[TencentCloudSDKException] code:ClientNetworkError message:[Errno -2] Name or service not known requestId:None
请问这是什么错误

**Comment by zqfan** [comment]
> [TencentCloudSDKException] code:ClientNetworkError message:[Errno -2] Name or service not known requestId:None
> 请问这是什么错误

把你填的endpoint发一下，这种是说域名解析失败了，你填的endpoint（域名）可能不正确

**Comment by Instantnoodles-madman** [comment]
endpoint = "ocr.tencentcloudapi.com"

**Comment by Instantnoodles-madman** [comment]
把你填的endpoint发一下，这种是说域名解析失败了，你填的endpoint（域名）可能不正确
你这里指的 endpoint是我的代理还是什么

**Comment by zqfan** [comment]
fixed by https://github.com/TencentCloud/tencentcloud-sdk-python/commit/db68d5e0f2d590dc64c5c7523cd7323d3a1bb8ff
