### ISSUE TITLE
金融云如何修改region地址呢

### ISSUE THREAD

**Issue by hujingguang** [TencentCloud/tencentcloud-sdk-python#38]

**Comment by zqfan** [comment]
像examples目录里那样，https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py，初始化Client的时候指定就可以了，域名和region都需要指定为金融区的
cvm.ap-shanghai-fsi.tencentcloudapi.com
ap-shanghai-fsi
