### ISSUE TITLE
signature  question

### ISSUE THREAD

**Issue by garspace** [TencentCloud/tencentcloud-sdk-python#39]
我已经将secret id和key换成我自己的了，但是不明白为什么还报签名的错误，
cred = credential.Credential(
    "xxx",
    "xxx")
httpProfile = HttpProfile()
httpProfile.endpoint = "ocr.tencentcloudapi.com"

clientProfile = ClientProfile()
clientProfile.httpProfile = httpProfile
client = ocr_client.OcrClient(cred, "ap-guangzhou", clientProfile)

req = models.GeneralBasicOCRRequest()
with open('E:\\dj\\pixel_link-master\\img\\415.jpg','rb') as f:
    img = f.read()
img_base64 = base64.b64encode(img)
req.ImageBase64 = img_base64
resp = client.GeneralBasicOCR(req)
print(resp.to_json_string())

错误信息如下：
  raise TencentCloudSDKException(code, message, reqid)
tencentcloud.common.exception.tencent_cloud_sdk_exception.TencentCloudSDKException: [TencentCloudSDKException] code:AuthFailure.SignatureFailure message:The provided credentials could not be validated. Please check your signature is correct. requestId:f5284213-7aa3-4e14-aff5-41866aab0ca1

**Comment by zqfan** [comment]
请检查自己的密钥是否有空格，少复制或者多了字符

**Comment by liny23** [comment]
用url可以，base64有问题

**Comment by zqfan** [comment]
如果是python3，注意base64出来的是字节而不是字符串，转换下应该就可以了。

**Comment by liny23** [comment]
from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
from tencentcloud.ocr.v20181119 import ocr_client, models
import base64
import os


def tobase64(file_path):
    f = open(file_path, 'rb')
    res = base64.b64encode(f.read())
    f.close()
    return res.decode()


def work(url):
    try:
        cred = credential.Credential("xxx", "xxx")
        httpProfile = HttpProfile()
        httpProfile.endpoint = "ocr.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        client = ocr_client.OcrClient(cred, "ap-shanghai", clientProfile)
        req = models.GeneralFastOCRRequest()
        # req.ImageUrl = url
        req.ImageBase64 = tobase64(url)
        resp = client.GeneralFastOCR(req)
        print(url, resp.to_json_string())

    except TencentCloudSDKException as err:
        print(err)


if __name__ == "__main__":
    f = open('ocr.txt', 'r')
    for line in f:
        work(line.strip('\n'))

我的代码是这样的，调用还是有这样的问题

**Comment by liny23** [comment]
`from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
from tencentcloud.ocr.v20181119 import ocr_client, models
import base64
import os


def tobase64(file_path):
    f = open(file_path, 'rb')
    res = base64.b64encode(f.read())
    f.close()
    return res.decode()


def work(url):
    try:
        cred = credential.Credential("AKID4ylQtCjF62nEUbrMr353lOr53q8H5aOD", "s89vU2LPEn6AyWxAE2Zr3e1LRI1VcV9X")
        httpProfile = HttpProfile()
        httpProfile.endpoint = "ocr.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        client = ocr_client.OcrClient(cred, "ap-shanghai", clientProfile)
        req = models.GeneralFastOCRRequest()
        # req.ImageUrl = url
        req.ImageBase64 = tobase64(url)
        resp = client.GeneralFastOCR(req)
        print(url, resp.to_json_string())

    except TencentCloudSDKException as err:
        print(err)


if __name__ == "__main__":
    f = open('ocr.txt', 'r')
    for line in f:
        work(line.strip('\n'))`
我的代码是这样的，还是一样的问题

**Comment by liny23** [comment]
from tencentcloud.common import credential
from tencentcloud.common.profile.client_profile import ClientProfile
from tencentcloud.common.profile.http_profile import HttpProfile
from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
from tencentcloud.ocr.v20181119 import ocr_client, models
import base64
import os


def tobase64(file_path):
    f = open(file_path, 'rb')
    res = base64.b64encode(f.read())
    f.close()
    return res.decode()


def work(url):
    try:
        cred = credential.Credential("xxx", "xxx")
        httpProfile = HttpProfile()
        httpProfile.endpoint = "ocr.tencentcloudapi.com"

        clientProfile = ClientProfile()
        clientProfile.httpProfile = httpProfile
        client = ocr_client.OcrClient(cred, "ap-shanghai", clientProfile)
        req = models.GeneralFastOCRRequest()
        # req.ImageUrl = url
        req.ImageBase64 = tobase64(url)
        resp = client.GeneralFastOCR(req)
        print(url, resp.to_json_string())

    except TencentCloudSDKException as err:
        print(err)


if __name__ == "__main__":
    f = open('ocr.txt', 'r')
    for line in f:
        work(line.strip('\n'))
代码是这样的，调用还是有问题

**Comment by zqfan** [comment]
@liny23 你的密钥已经泄漏了。请到官网控制台-访问管理-密钥管理禁用此密钥。你是python3的环境吗？base64.b64encode在python2下是字符串，在python3下是字节。SDK要求此字段是字符串，在python3下你得把base64.b64encode得到的返回转为字符串。

**Comment by samxcode** [comment]
关注，同一个问题，url可以，BASE64不行，麻烦看下

**Comment by samxcode** [comment]
> @liny23 你的密钥已经泄漏了。请到官网控制台-访问管理-密钥管理禁用此密钥。你是python3的环境吗？base64.b64encode在python2下是字符串，在python3下是字节。SDK要求此字段是字符串，在python3下你得把base64.b64encode得到的返回转为字符串。

关注，和楼主同一个问题，url可以，BASE64不行，麻烦看下
