### ISSUE TITLE
cdb models InstanceInfo 有问题

### ISSUE THREAD

**Issue by anyharding** [TencentCloud/tencentcloud-sdk-python#4]
tencentcloud.cdb.v20170320.models.py
cdb models.py  InstanceInfo  _deserialize()  1880行
报错信息
[TencentCloudSDKException] code:'list' object has no attribute 'get' message:'list' object has no attribute 'get' requestId:None

RoVipInfo 返回是个list, 被当成字典处理

**Comment by zqfan** [comment]
感谢反馈，已经修复：https://github.com/TencentCloud/tencentcloud-sdk-python/commit/2c7e6e35b0d011bd4606f4d2c8737af2c1c85dde
