### ISSUE TITLE
example使用错误

### ISSUE THREAD

**Issue by llongday** [TencentCloud/tencentcloud-sdk-python#41]
复制的tencentcloud-sdk-python/examples/ecc/v20181213/ecc_ocr.py来测试
 错误提示
[TencentCloudSDKException] code:InvalidParameter.InputError message:传入的参数有误 requestId:63727bdb-1db2-43e1-bb05-f099c1b1b00a
其中sid和sk是我自己的

**Comment by zqfan** [comment]
业务反馈是后台有问题，已经修复了，请重试。如没有解决，可重新打开本问题。
