### ISSUE TITLE
[TencentCloudSDKException] code:AuthFailure.SignatureFailure message:The provided credentials could not be validated because of exceeding request size limit, please use new signature method `TC3-HMAC-SHA256`. 

### ISSUE THREAD

**Issue by panapple** [TencentCloud/tencentcloud-sdk-python#42]
使用五官定位api,代码是API explorer自动生成的，请问该怎么使用 signature method `TC3-HMAC-SHA256'

**Comment by zqfan** [comment]
ClientProfile里有选项指定https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py#L26。升级到最新的版本则默认使用TC3-HMAC-SHA256
