### ISSUE TITLE
测试vod出错，请问怎么解决

### ISSUE THREAD

**Issue by CachCheng** [TencentCloud/tencentcloud-sdk-python#44]
[TencentCloudSDKException] code:InternalError message:service internal error requestId:27b7dfcd-8d6c-4f13-999f-d94b945f259a

**Comment by zqfan** [comment]
这是vod内部出了问题，SDK无法解决。到腾讯云官网控制台，工单，提工单给云点播vod这个产品，把这个返回贴给他们。
