### ISSUE TITLE
python示例代码：上传一段视频，调用视频内容分析接口，获取视频标签信息的代码有吗？

### ISSUE THREAD

**Issue by CachCheng** [TencentCloud/tencentcloud-sdk-python#45]

**Comment by zqfan** [comment]
SDK只是对产品提供的接口的封装。
至于如何运用聪明才智，将接口的原子功能组合成强大的功能，每个业务、每个场景都有区别，需要对业务逻辑和产品特性较高的把握能力，不是SDK力所能及的。
如果你所说的是通用的需求，可以找对应的产品咨询下，也许他们会乐意提供类似代码放进仓库。
