### ISSUE TITLE
cdb缺少DescribeProductConfig接口

### ISSUE THREAD

**Issue by anyharding** [TencentCloud/tencentcloud-sdk-python#5]
DescribeProductConfig
https://cloud.tencent.com/document/product/409/16776

**Comment by zqfan** [comment]
https://cloud.tencent.com/document/product/409/16776这个链接的产品是postgres，不是cdb。
postgres该接口参见 https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tencentcloud/postgres/v20170312/postgres_client.py#L112
