### ISSUE TITLE
在python3中无法正常打开open函数

### ISSUE THREAD

**Issue by lidianxiang** [TencentCloud/tencentcloud-sdk-python#54]
在使用python的SDK进行asr录音文件的转换，使用官网提供的代码后， 可以用python2进行正常的运行，但是在**python3**中，无法正常的打开open函数，提示“UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 5: ordinal not in range(128)”,尝试将编码方式改成utf-8和gbk等方式也无法正常运行，将模式改成rb方式也无法正常运行。不知道是哪里的问题。

**Comment by zqfan** [comment]
非SDK相关的问题。
可能的原因是文件在写入时并非二进制的，所以读取时按照编码方式以及二进制方式都无法读取。你可以先确定下文件内容的编码，再用对应的编码读取试试。
