### ISSUE TITLE
营业执照识别如何调用本地服务器图片

### ISSUE THREAD

**Issue by cp-xiaoma** [TencentCloud/tencentcloud-sdk-python#59]
以下方法只能识别存储在对象存储中的图片，怎么配置才能识别存储在本地服务器的图片呢？
req = models.BizLicenseOCRRequest()
params ={"ImageUrl": "https://c.myqcloud.com/" + img}
req.from_json_string(params)

**Comment by zqfan** [comment]
先上传到cos吧，看这里的文档https://cloud.tencent.com/document/api/866/36215 还可以用base64的，你先读取本地文件，将内容做base64，字符串传进去吧

**Comment by hn18001** [comment]
@zqfan 请问传入base64这种方式调用，有示例代码吗？

**Comment by zqfan** [comment]
我也不太清楚业务逻辑。像这个接口有个ImageBase64的话，你直接with open(文件路径）读取文件内容，然后base64.b64encode(data)就可以了，注意python3可能需要转为string传入禁区

**Comment by cp-xiaoma** [comment]
感谢回复，识别本地文件的部分代码如下：
url_img = os.path.join('F:\static\',1.jpg)
with open(url_img,'rb') as f:
       new_img = f.read()
img_base64 = base64.b64encode(new_img)
img_base64 = img_base64.decode("utf-8")
params = {"ImageBase64":img_base64}
