### ISSUE TITLE
cdb 的接口有问题

### ISSUE THREAD

**Issue by pc10201** [TencentCloud/tencentcloud-sdk-python#6]
# 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey
        cred = credential.Credential(secret_id, secret_key)

        # 实例化要请求产品(以cdb为例)的client对象
        client = cdb_client.CdbClient(cred, region)

        # 实例化一个请求对象

        req = models.DescribeDBInstancesRequest()

        # 通过client对象调用想要访问的接口，需要传入请求对象
        resp = client.DescribeDBInstances(req)

**Comment by zqfan** [comment]
请问具体是什么问题呢？
该接口曾有一个RoVipInfo类型不对的问题，但是现在已经修复了。

**Comment by pc10201** [comment]
已经修复了
