### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by rexana3** [TencentCloud/tencentcloud-sdk-python#60]
data = str(fwave.read())
    dataLen = len(data)
    base64Wav = base64.b64encode(data)

  File "C:\Users\czy\Anaconda3\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by moyemoji** [comment]
+1

**Comment by rexana3** [comment]
Thank you for your relpy!Can you speak chinese?I put my code in the attachment.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"moyemoji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 下午5:55
收件人:&nbsp;"TencentCloud/tencentcloud-sdk-python"<tencentcloud-sdk-python@noreply.github.com&gt;;
抄送:&nbsp;"陈柔洁"<497014168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TencentCloud/tencentcloud-sdk-python] a bytes-like object is required, not 'str' (#60)





 
+1

**Comment by zqfan** [comment]
@rexana3 python3 base64.b64encode requires a byte input rather than a string, which means you don't need str(fwave.read()), just fwave.read() should work
