### ISSUE TITLE
调用python sdk做iot的固件升级出现异常，有时候又可以？

### ISSUE THREAD

**Issue by Michalhu** [TencentCloud/tencentcloud-sdk-python#62]
使用腾讯云api的python sdk调用物联网的固件升级，直接用api explorer在线生成的python代码，执行后，出现如下提示：
![python sdk](https://user-images.githubusercontent.com/38523038/80187626-8a088880-8642-11ea-8950-f15bce528862.png)

**Comment by zqfan** [comment]
你的sdk版本可能比较低，先升级到最新看看。api explorer是默认用最新的。
下次打码可以再打重一点，你这个还是能看到的
