### ISSUE TITLE
请问有支持python37的计划么？

### ISSUE THREAD

**Issue by DachuanZhao** [TencentCloud/tencentcloud-sdk-python#67]
RT

**Comment by zqfan** [comment]
应该是支持的，在ubuntu16.04和centos7下测试了python3.7，几个简单的单元测试都通过了。
请问你是遇到什么具体的问题了吗？

**Comment by DachuanZhao** [comment]
> 应该是支持的，在ubuntu16.04和centos7下测试了python3.7，几个简单的单元测试都通过了。
> 请问你是遇到什么具体的问题了吗？

没有，我就是先来翻翻文档，看上面只支持到36，我们现在的版本是37，所以来问问

**Comment by zqfan** [comment]
文档已经更新了
