### ISSUE TITLE
由于请求包大小超过限制，请求签名验证失败，请使用新的签名方法 `TC3-HMAC-SHA256

### ISSUE THREAD

**Issue by yuemengrui** [TencentCloud/tencentcloud-sdk-python#68]
增值税发票识别无法使用，文档规定不超过3M，使用1.7M的图片依然无法使用

**Comment by zqfan** [comment]
SDK默认使用的就是TC3-HMAC-SHA256
请检查ClientProfile实例的signMethod是不是指定了HmacSHA256或者HmacSHA1，将其删除使用默认的即可

**Comment by stayrea1** [comment]
同样的问题，在OCR识别里面默认是HmacSHA256，将ClientProfile实例的signMethod改为TC3-HMAC-SHA256就行了
