### ISSUE TITLE
代码无法执行.麻烦更新代码和在readme说明一下

### ISSUE THREAD

**Issue by qdlimit** [TencentCloud/tencentcloud-sdk-python#69]
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py
这个代码目前无法执行.
检测到secret ID和KEY的地方语法有变，调用的接口域名也有变化
麻烦更新一下代码内容和在readme说明一下.可能其他实例代码也无法执行,麻烦检查一下

**Comment by hapsyou** [comment]
> https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py
> 这个代码目前无法执行.
> 检测到secret ID和KEY的地方语法有变，调用的接口域名也有变化
> 麻烦更新一下代码内容和在readme说明一下.可能其他实例代码也无法执行,麻烦检查一下

麻烦贴一下报错信息，顺便将代码发送至我的邮箱（还请去掉秘钥等私密信息），因为我这里执行了一下是OK的

**Comment by zqfan** [comment]
将这里的https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py#L14  读取环境变量改为真实密钥就可以了
接口域名有很多个，主要是为了访问就近加速，从功能角度使用任意一个并无差别

**Comment by qdlimit** [comment]
> > https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/examples/cvm/v20170312/describe_instances.py
> > 这个代码目前无法执行.
> > 检测到secret ID和KEY的地方语法有变，调用的接口域名也有变化
> > 麻烦更新一下代码内容和在readme说明一下.可能其他实例代码也无法执行,麻烦检查一下
> 
> 麻烦贴一下报错信息，顺便将代码发送至我的邮箱（还请去掉秘钥等私密信息），因为我这里执行了一下是OK的

你的邮箱是?

**Comment by zqfan** [comment]
去掉密钥直接贴这里吧，其他敏感的如账号等都可以去掉或者打码

**Comment by zqfan** [comment]
因长时间未回复关闭
有需要请提供信息后再重新打开
