### ISSUE TITLE
tencentcloud.nlp.v20190408 缺失 TextSimilarityRequest

### ISSUE THREAD

**Issue by codemayq** [TencentCloud/tencentcloud-sdk-python#70]
人工智能-自然语言处理的 句子相似度 API，在SDK中没有，还请补充

**Comment by zqfan** [comment]
升级下sdk版本到最新吧
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tencentcloud/nlp/v20190408/nlp_client.py#L447
