### ISSUE TITLE
asr  demo代码执行出错

### ISSUE THREAD

**Issue by chinazoujy** [TencentCloud/tencentcloud-sdk-python#71]
https://cloud.tencent.com/document/product/1093/35731
通过本地语音上传方式请求的demo代码

报错如下：
Traceback (most recent call last):
  File "tencent_asr.py", line 24, in <module>
    data = str(fwave.read())
  File "/home/~~/anaconda3/envs/spider/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte

音频 file结果：
RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz

**Comment by huitang** [comment]
我也遇到一样的问题 请问你怎么解决的 多谢

**Comment by zqfan** [comment]
参考这里的代码https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tests/integration/ocr/test_general_accurate_ocr.py读取文件并base64

python3下base64库b64encode返回的是byte而不是str，需要decode下

**Comment by huitang** [comment]
> 参考这里的代码[https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tests/integration/ocr/test_general_accurate_ocr.py读取文件并base64](https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tests/integration/ocr/test_general_accurate_ocr.py%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6%E5%B9%B6base64)
> 
> python3下base64库b64encode返回的是byte而不是str，需要decode下
晕死了
现在遇到的是这个问题 请帮忙看一下怎么回事儿 多写了
 code:InternalError message:内部服务错误，请稍后重试。

**Comment by zqfan** [comment]
请到控制台工单系统提工单到对应业务

**Comment by chinazoujy** [comment]
> 我也遇到一样的问题 请问你怎么解决的 多谢

`fwave = open(audio_fname, "rb")
 38             data = fwave.read()
 39
 40             dataLen = len(data)
 41             base64Wav = str(base64.b64encode(data), "utf-8")
 42
 43             req = models.CreateRecTaskRequest()
 44             params = {"EngineModelType":"16k_zh_video",
 45                       "ChannelNum":1,
 46                       "ResTextFormat":0,
 47                       "SourceType":1,
 48                       "Data":base64Wav,
 49                       "DataLen":dataLen }
`

**Comment by chinazoujy** [comment]
> 我也遇到一样的问题 请问你怎么解决的 多谢

`fwave = open(audio_fname, "rb")`
`data = fwave.read()`
`base64Wav = str(base64.b64encode(data), "utf-8")`
base64Wav 可以作为参数"Data" 直接传

**Comment by zqfan** [comment]
python3下才需要把base64.b64encode返回的字节转为字符串
