### ISSUE TITLE
python版本的本地文件上传识别示例代码是跑不通的

### ISSUE THREAD

**Issue by bluceGYF** [TencentCloud/tencentcloud-sdk-python#73]
![image](https://user-images.githubusercontent.com/34001296/87011479-8c6a8f80-c1fa-11ea-8b9f-b1f0aa68325a.png)
读文件不以二进制读是报编码问题，ignore之后，还是跑不通的，下面base64.b64encode(data)这里又要二进制了，传了之后里面还会报错的，希望更新下。

**Comment by zqfan** [comment]
open mode=rb
python3 base64得到的是byte对象，要decode一下，参考：https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tests/integration/ocr/test_general_accurate_ocr.py#L23
