### ISSUE TITLE
ASR 官网识别本地语音例子不work

### ISSUE THREAD

**Issue by huitang** [TencentCloud/tencentcloud-sdk-python#75]
https://cloud.tencent.com/document/product/1093/35734
就是这里本地的例子出错 请帮忙看一下多谢

**Comment by zqfan** [comment]
看起来文档中给的是python2的用法
open mode=rb
python3 base64得到的是byte对象，要decode一下，参考：https://github.com/TencentCloud/tencentcloud-sdk-python/blob/master/tests/integration/ocr/test_general_accurate_ocr.py#L23

**Comment by huitang** [comment]
感谢 跑通了
