### ISSUE TITLE
api 都没文档的？

### ISSUE THREAD

**Issue by jellyhappy** [TencentCloud/tencentcloud-sdk-python#90]
这么多文件夹 去哪找对应的模块？

**Comment by zqfan** [comment]
每个产品都在api文档中介绍了自己的域名（endpoint），域名的首段一般就是产品缩写名，也就是sdk中的模块名。例如云服务器（Cloud Virtual Machine，缩写cvm)的域名是cvm.tencentcloudapi.com，他在sdk中的模块名就是cvm。
