### ISSUE TITLE
怎么获取表格图片识别的返回结果 为python对象格式？

### ISSUE THREAD

**Issue by jcyrss** [TencentCloud/tencentcloud-sdk-python#91]
找遍了腾讯云的文档也没有找到

对比百度云的API， 清晰易懂。 

把一个简单的东西搞复杂，确实是你们的本事。好像不这样不能显示你们的高大上似的。

哎

**Comment by jcyrss** [comment]
还是看库代码找到了

```py
resp = client.RecognizeTableOCR(req)
resp.TableDetections # 大哥，为啥这么重要的东西没有文档提起，要自己看库源代码呀？
````

**Comment by zqfan** [comment]
可是，这不是ide里直接点一下就能点出来的吗？或者在这个类定义里就直接写了的啊

**Comment by jcyrss** [comment]
> 可是，这不是ide里直接点一下就能点出来的吗？或者在这个类定义里就直接写了的啊

这是你们的SDK啊，你看过哪个成熟的sdk需要用户IDE去看库源代码才能用的！！！！！文档是干什么用的？

这是 腾讯这种大厂的 战略级产品 该做的样子？！！！！ 震惊！！！！

**Comment by zqfan** [comment]
恰恰相反，成熟的SDK应当可以摆脱文档就能指引使用者完成调用。想想看一个SDK连个注释都没有，竟然要到某个链接的网页里去看说明，链接没了呢？直接啃代码吗？哪天人家在官网把文档内容改了，你连个对质的地方都没有。真是弃珠玉为糟粕。

SDK的提示已经十分完善了，这是我直接拿readme里的例子，截图中IDE都有和当时官网文档内容一致的提示
![image](https://user-images.githubusercontent.com/2180987/125077163-5e60a980-e0f3-11eb-86ea-83216c9c5448.png)
![image](https://user-images.githubusercontent.com/2180987/125077273-7f28ff00-e0f3-11eb-9662-ec61e81adaeb.png)
![image](https://user-images.githubusercontent.com/2180987/125077324-8c45ee00-e0f3-11eb-8be7-d68cb36b8662.png)

接口文档在官网找不到，你应该登录到控制台工单系统给对应的产品提单（这里你问的应该是ocr这个产品的），问问他们为何在官网把接口文档给搞没了。跑到SDK github页面这里打这么多惊叹号，解决不了你的问题

**Comment by jcyrss** [comment]
> 想想看一个SDK连个注释都没有，竟然要到某个链接的网页里去看说明，链接没了呢？直接啃代码吗？哪天人家在官网把文档内容改了，你连个对质的地方都没有。

我说的是文档关键信息没有 这是问题 ， 不是说 SDK代码里面不需要注释。 你这是什么理解能力。
