### ISSUE TITLE
这里格式化数据的时候能不能返回UserScript字段，我们需要依赖这个字段

### ISSUE THREAD

**Issue by betaincao** [TencentCloud/tencentcloud-sdk-python#93]
https://github.com/TencentCloud/tencentcloud-sdk-python/blob/29bb27d90ced284ae90735fe3f9cb1fcfda8a8e1/tencentcloud/tke/v20180525/models.py#L4607
查询节点池信息的SDK中需要返回UserScript字段，可以支持吗？

**Comment by zqfan** [comment]
目前SDK仅解析了在文档中声明了的字段，https://cloud.tencent.com/document/api/457/49431 我看文档里都没提到UserScript参数呀

**Comment by betaincao** [comment]
> 目前SDK仅解析了在文档中声明了的字段，https://cloud.tencent.com/document/api/457/49431 我看文档里都没提到UserScript参数呀

是的，但是创建节点池的时候支持输入UserScript参数，查询的时候为什么要限制这个呢？把这个参数返回比较好。

**Comment by zqfan** [comment]
SDK无法解决这个问题，你需要到控制台右上角提工单给容器产品，让他们接口支持这个参数，只要文档中有这个字段，SDK就自动会有了
