### ISSUE TITLE
咨询下，请问有伸缩组，弹性伸缩的案例吗？

### ISSUE THREAD

**Issue by gezhuangsheng** [TencentCloud/tencentcloud-sdk-python#95]
咨询下，请问有伸缩组，弹性伸缩的案例吗？求链接

**Comment by zqfan** [comment]
没看懂你到底是想要什么，也许可以试试api explorer这个工具，https://console.cloud.tencent.com/api/explorer?Product=as&Version=2018-04-19&Action=DescribeAutoScalingGroups&SignVersion=

**Comment by gezhuangsheng** [comment]
![image](https://user-images.githubusercontent.com/10205764/116043014-b6197800-a6a1-11eb-80c3-2dc12d7c2db0.png)

**Comment by gezhuangsheng** [comment]
example 里面有没有伸缩组的案例

**Comment by zqfan** [comment]
这些示例实际上使用api explorer也能生成出来，如果你的确需要更复杂的组合示例，请到控制台工单系统提单给弹性伸缩业务，让他们增加示例。
